export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';

export const CONVERSATION_CLICK = 'CONVERSATION_CLICK';
export const CONVERSATION_CLICK_ADD_TAG = 'CONVERSATION_CLICK_ADD_TAG';

